### ISSUE TITLE
can use java version 8 ?

### ISSUE THREAD

**Issue by iyangpengyu** [mmornati/springboot-osgi-sample#15]
the project version is jdk15, but i want use jdk8 can`t work ;  i want konw why ?

**Comment by mmornati** [comment]
In the end I guess I just used some code specific to JDK >11 in this exemple. But all the libs, and mainly the Osgi one which is interesting here, it is working with jdk8.
So yes, you can make it jdk8 compatible.

It should be better, for your application, to upgrade to newer LTS, 11 or 17, cause they are having lot of improvements in the JVM itself.

**Comment by iyangpengyu** [comment]
Thank you very much for your reply, but it does not seem to solve my problem. 

When I used jdk1.8.0_181, I reduced the three grammars of jdk>8. 
The "mvn clean install" command was execued successful, but the "jar -jar xxx.jar" command has error. 

It is found that only sample-bundle-src can be found, but sample-bundle cannot be found. 
Error stack says:
org.osgi.framework.bundleexception: unable to resolve sample-bundle[6](R 6.0):missing requirement [sample-bundle[6](R 6.0)] org.wiring.package;(osgi.wiring.package=com.mornati.sample.commons.plugins)

just like this error : https://stackoverflow.com/questions/68284705/missing-requirement-osgi-wiring-package-osgi-wiring-package-org-osgi-framewo 

the error is:
~~~
2021-12-22 16:33:12.021 INFO 12524 ---[ixDispatchQueue] c.m.s.service.SpringAwareBundleListener Bundle sample-bundle-scr:0.0.1.202112220832 changed state to Installed - Type: Uninstalled

Error while starting bundle: file:/D:/tmp/a_nctb/A_ypy_code/springboot-osgi-sample-main/plugins/sample-bundle-0.0.1-SNAPSHOT.jar: org.osgi.framework.BundleException:Unable to resolve sample-bundle [6](R 6.0): missing requirement [s

ample-bundle [6](R 6.0)] osgi.wiring-package; (osgi.wiring.package=com.mornati.sample.commons.plugins) Unresolved requirements: [[sample-bundle [6](R 6.0)] osgi.wiring-package; (osgi.wiring.package=com.mornati.sample.commons.plugins

)]

org.osgi.framework.BundleException: Unable to resolve sample-bundle [6](R 6.0): missing requirement [sample-bundle [6](R 6.0)] osgi.wiring-package; (osgi.wiring.package=com.mornati.sample.commons.plugins)

Unresolved requirements: [[sample-bundle [6](R 6.0)] osgi.wiring-package; (osgi.wiring.package=com.mornati.sample.commons.plugins)]

at org.apache.felix.framework.Felix.resolveBundleRevision(Felix. java:4398)

at org.apache.felix.framework.Felix.startBundle(Felix. java:2308) at org.apache.felix.framework.BundleImp1. start(BundleImp1. java:1007)

at org-apache.felix.fileinstall. internal.DirectoryWatcher.startBundle(DirectoryWatcher. java:1260) at org-apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher. java:1233) at org-apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) at org-apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)

at org.apache.felix.fileinstall.internal.DirectoryWatcher. run(DirectoryWatcher. java:316) 2021-12-22 16:33:12.041 INFO 12524 --[ixDispatchQueue] c.m.s.service.SpringAwareBundleListener BundLe sample-bundle-scr:0.0.1.202112220832 changed state to Starting - Type:Active

2021-12-22 16:33:12.093 INFO 12524 -- [ixDispatchQueue] c.m.s.service.SpringAwareBundleListener Bundle sample-bundle-scr:0.0.1.202112220832 changed state to Active - Type: Installed


~~~
